### ISSUE TITLE
Wrong GOBIN path when using extension

### ISSUE THREAD

**Issue by alexandreLamarre** [kralicky/protols#1]
Probably user error but : 

.vsix extension doesn't look up protols properly:
```
[Error - 2:01:23 PM] protols client: couldn't create connection to server.
Launching server using command /home/alex/go/bin/protols failed. Error: spawn /home/alex/go/bin/protols ENOENT
```
but `go env` has : 

```
GOBIN='/usr/bin'
```

```
❯ which protols
/usr/bin/protols
```

and i checked vscode is loading the correct GOBIN by using `Go : Locate configured go tools`

which has : 
```
go env
Workspace Folder (protols): /home/alex/repos/protols
	GO111MODULE='auto'
	GOARCH='amd64'
	GOBIN='/usr/bin'
//....
```

**Comment by kralicky** [comment]
Fixed in https://github.com/kralicky/protols/commit/91b11fc1e10d93f6f72c1c7b9f5ffa75f475a72f, let me know if this works
